export const LABELS_FR = {
  common: {
    loading: 'Chargement...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    back: 'Retour',
    confirm: 'Confirmer',
  },
  patientSpace: {
    title: 'Espace patient',
    tabs: {
      file: 'Dossier',
      appointments: 'Rendez-vous',
      documents: 'Documents à signer',
    },
    header: {
      child: 'Enfant',
      nextAppointment: 'Prochain RDV',
      actionRequired: 'Action requise',
      noUpcomingAppointment: 'Aucun rendez-vous à venir',
    },
    guardians: {
      parent1: 'Parent 1',
      parent2: 'Parent 2',
      phoneVerified: 'Téléphone vérifié',
      phoneUnverified: 'Téléphone non vérifié',
      requestOtp: 'Envoyer le code',
      verifyOtp: 'Valider',
      otpPlaceholder: 'Code SMS',
    },
    appointments: {
      upcoming: 'RDV à venir',
      history: 'Historique RDV',
      schedule: 'Planifier un RDV',
      scheduleHint: 'Sélectionnez une date et un créneau pour confirmer le rendez-vous.',
      typePreconsultation: 'Consultation pré-opératoire',
      typeAct: 'Acte',
      modeVisio: 'Visio',
      modeInPerson: 'Présentiel',
    },
    documents: {
      title: 'Documents à signer',
      checklistTitle: 'Checklist',
      progressCases: (done, total) => `${done}/${total} cases`,
      complete: 'Complet',
      incomplete: 'À compléter',
      signature: {
        title: 'Actions de signature',
        signRemote: 'Signer à distance (OTP SMS)',
        signCabinet: 'Signer en cabinet',
        openLink: 'Ouvrir le lien',
        sendLink: 'Envoyer le lien',
        downloadSigned: 'Télécharger signé',
        downloadEvidence: 'Télécharger preuve',
      },
      reasons: {
        checklistIncomplete: 'Checklist incomplète.',
        phoneNotVerified: 'Téléphone non vérifié (requis pour signer à distance).',
        featureUnavailable: 'Fonctionnalité non disponible pour le moment.',
        missingAppointment: 'Sélectionnez un rendez-vous pour afficher les documents.',
      },
    },
    dossier: {
      childIdentityTitle: "Identité de l'enfant",
      childFirstName: 'Prénom',
      childLastName: 'Nom',
      childBirthDate: 'Date de naissance',
      childWeightKg: 'Poids (kg)',
      childMedicalNotes: 'Notes médicales',
      guardiansTitle: 'Parents / responsables légaux',
      parentName: (label) => `Nom ${label}`,
      parentEmail: (label) => `Email ${label}`,
      parentPhone: (label) => `Téléphone ${label}`,
      smsOptin: (label) => `Recevoir les codes SMS sur le numéro du ${label.toLowerCase()}`,
      parentalAuthorityAck:
        "Je comprends que le consentement des deux titulaires de l'autorité parentale est obligatoire.",
      saveCase: 'Enregistrer le dossier',
    },
  },
};

